project:
  type: book
  output-dir: docs

book:
  title: "Restaurant Profit Readiness Guide"
  author: "Ben Halperin"

  chapters:
    - index.md
    - intro.qmd
    - chapter01.qmd
    - chapter02.qmd
    - chapter03.qmd
    - chapter04.qmd
    - chapter05.qmd
    - chapter06.qmd
    - chapter07.qmd
    - chapter08.qmd
    - chapter09.qmd
    - chapter10.qmd
    - chapter11.qmd
    - chapter12.qmd
    - chapter13.qmd
    - chapter14.qmd
    - chapter15.qmd
    - chapter16.qmd
    - chapter17.qmd
    - chapter18.qmd
    - chapter19.qmd
    - chapter20.qmd
    - summary.qmd
    - 99-epilogue.qmd

format:
  html:
    toc: true
    theme: cosmo
